### PR TITLE
Update to @prismicio/client

### PR DESCRIPTION
**Pull request by pvpg**
Updated kit to use `@prismicio/client`

### CODE REVIEW

**Review by lihbr — COMMENTED** [review]
LGTM, can we also take advantage of this update to remove the redundant package-lock.json and gitignore it? Maintaining one along a yarn.lock is not a ideal :(

**Comment by PaulinaVPG** [comment]
@lihbr I removed the yarn file.

**Comment by Gholgot** [comment]
@lihbr do you think it can be merged ?

**Comment by lihbr** [comment]
There's some minor clean up that needs to be done before, the thing that bugged me and explains why this is still on hold is that:
1. @prismicio/client has still not landed on master: https://github.com/prismicio/prismic-javascript/pull/143
2. @prismicio/client is dropping node 8 support, this introduces a breaking change for people using the kit relying on that version

I'm happy to have a chat to sort that out!

**Pull request merged**
