### PR TITLE
TypeScript support & removal of template compiler

### PR DESCRIPTION
**Pull request by WipeAir**
### Changes
* #5 Rewritten the entire plugin with TypeScript. (No breaking API changes were made)
* #6 Replaced Vue SFCs with render function components. (Therefore it's no longer required to load the full Vue build with the template compiler)
* Added yarn as package manager (Therefore the `yarn.lock` file, package-lock.json is still in-sync)
* Optimized the rollup configuration. 
  * Removed babel, because it's no longer really needed b/c of TypeScript.
  *  Added Terser for minification.
  * Updated version of rollup and plugins.
* Removed `dist` folder from the git repository. (Should be enough to have it in the published module)

This version is currently available on npm as `@auritylab/prismic-vue`

If you have any further questions about the changes don't hesitate to ask!

### CODE REVIEW

**Comment by blieque** [comment]
Out of curiosity, is there much advantage to adding Yarn to a relatively small package like this?

**Comment by WipeAir** [comment]
I don't think so, maybe some parts are faster, but I think it's mostly personal preference.

**Comment by Raph22** [comment]
Hi WipeAir,
Thanks all lot for your contribution, I appreciate the hard work and the effort that you put into it.

However, our strategy is not to build our Vue SDK in TypeScript at the moment. We want to encourage contribution, and we feel that TypeScript can block the contribution from some of our users.

We are really into Typescript and use it internally, but we built this kit without it on purpose what we prefer to do is to provide a type definition file and declare it in the type field of the package.json.

We feel that this is already a great help when building your typescript project without making the contributions in our kits more difficult.

If this is important for you, I’d recommend doing a PR since this is not on our priority list at the moment.
For others contributions, can you split them in several PR?

Many thanks in advance.

**Comment by blieque** [comment]
Encourage contribution? You've only ever merged one PR to this package, and have only closed two of the six issues ever opened.

One of the main selling points of TypeScript is that it's incrementally adoptable; it really doesn't make contribution much harder.

Additionally, this PR fixes your components that currently require the compiler Vue.js build. By slightly restructuring these components, WipeAir has saved everyone ~25 kB in their bundles.

Please reconsider this PR. Dismissing it entirely for not using ECMAScript is silly. Can you guarantee that it would be accepted if it was written in ECMAScript?

**Comment by arajay** [comment]
> what we prefer to do is to provide a type definition file and declare it in the type field of the package.json

where can i get this?

**Pull request closed without merging**
